### ISSUE TITLE
Customizations

### ISSUE THREAD

**Issue by nrxofficial** [axeleroy/self-host-planning-poker#94]
Hey,

it would be nice to have some options to customize the UI.
For example:
- accent color
- logo
You could solve this via environmental variables in the docker compose.

Also a possibility to add custom game decks.

Thank you! We use your Scrum Poker every week! The only good one (with selfhosting) that isnt overloaded with crap!

**Comment by axeleroy** [comment]
Hello!

Sorry for the late response, I left the project on the side for the past six months and decided to pick it up today.

Customization were never part of my vision for the project as I wanted it to be as simple as possible, while having a distinct visual identity. In the other hand, I completely understand the desire to customize it to match their company's brand or specificities.

So if you or anyone else is willing to put the efforts into building these customization features I'll gladly accept a pull request :smile: 

In that goal, I'll give some pointers as to if and how these features can be achieved:
 * **Accent color**: There are two ways to do it
   1. Edit `angular/src/styles.scss` to replace the green by something else and then build a custom Docker image. Not ideal as you would have to build a new image for every new release, but it does not need any development effort. It also gives greater control so someone can match their company's exact color scheme.
       ```scss
      $primary: #dc3545; // Bootstrap's red
      $enable-shadows: true;
      $color-mode-type: media-query;
      
      @import 'bootstrap/scss/bootstrap';
      
      :root {
        --card-color: #{$red-500};
      }
      
      .bg-primary {
        background-color: $red-400 !important;
        color: white !important;
        .text-muted {
          color: $gray-400 !important; // Might want to change that value for contrast
        }
      }
      ```
   2. Bootstrap 5.3 introduced [custom color modes](https://blog.getbootstrap.com/2023/05/30/bootstrap-5-3-0/#custom-color-modes) which would even allow changing colors dynamically! But I have no idea how to set one color mode by default from Docker. It would also restrict colors to a set list of themes, thus you couldn't match someone's company color scheme
 * **Custom logo**: I believe you could overwrite the logo by mounting a bind-mount on `/app/static/assets/icon.svg` and `/app/static/assets/favicon`
   ```yaml
    version: "3"
    services:
      planning-poker:
        image: axeleroy/self-host-planning-poker:latest
        ports:
          - 8000:8000
        volumes:
          - planning-poker-data:/data
          - /path/to/icon.svg:/app/static/assets/icon.svg
          - /path/to/favicon-folder:/app/static/assets/favicon
    volumes:
      planning-poker-data: {}
   ```
* **Custom decks**: Unfortunately, that would be hard without a major refactoring. Decks are currently hard-coded into the back-end and front-end. I also had the extremely bad idea to represent each card value in the back-end as numbers instead of enumeration values, which currently makes values such as `?` and `☕` impossible to implement.
